# Site settings

title: Federal Public Key Infrastructure Guides
name: Federal Public Key Infrastructure Guides
email: fpki@gsa.gov
author:
    name: FICAM
description: Information on the US Federal Public Key Infrastructure (FPKI)
highlighter: rouge
repo_url: https://github.com/GSA/fpki-guides
baseurl: '/fpki-guides'
branch: federalist-pages
# Federalist overwrites the site.branch value when deploying
# the site.branch was used in dynamic link generation for objects like Edit Page
# we want the dynamic links to send users to the staging branch.  Adding new site variable to ensure federalist doesn't overwrite.
editbranch: staging
system_notification_url: http://github.com/djpackham/fpki-guides/issues/new?title=System%20Notification%20for%3A%20%3CYour%20Organization%3E&amp;body=%23%23%23%23%20Notice%20Date:%0A%3CEnter%20Notice%20Date%20Here%3E%0A%0A%23%23%23%23%20System:%0A%3CEnter%20System%20Name%20Here%3E&amp;labels[]=System%20Notification


# Links
# List links that you would like to appear on the top navigation bar here
navbar:
- title: IDmanagement.gov
  description: Idmanagement.gov
  url: https://www.idmanagement.gov
- title: Federal ICAM Architecture
  description: Federal ICAM Architecture
  url: https://arch.idmanagement.gov
- title: PIV Guides
  description: PIV Guides
  url: https://piv.idmanagement.gov
#- title: Federal PKI Guides
#  description: Federal PKI Guides
#  url: https://github.com/gsa/fpki-guides

# Build settings
markdown: kramdown

#kramdown:
#  input: GFM
# syntax_highlighter: rouge

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Introduction
  url: ''
  internal: true
  coll: false
- text: Certification Authorities
  url: ca
  internal: true
  coll: false
- text: Certificates and CRLs
  url: crls
  internal: true
  coll: false
# - text: Certificate Policies
  # url: policyobjects
  # internal: true
  # coll: false
- text: Trust Stores
  url: truststores
  internal: true
  coll: false
- text: Useful Tools
  url: tools
  internal: true
  coll: false
- text: Change Notifications
  url: notifications
  internal: true
  coll: false
#https://github.com/jekyll/jekyll/issues/2346
#- text: Engineer Guides
# url: engineer/
# internal: true
# coll: true
# collname: engineer
#- text: FAQ
#  url: faq
#  internal: true
#  coll: true
#  collname: faq
#- text: About PKI
#  url: pki
#  internal: true
#  coll: false
#  collname: pkifundamentals
#- text: Glossary
#  url: glossary
#  internal: true
#  coll: false
- text: Contribute
  url: contribute
  internal: true
  coll: false



#https://github.com/jekyll/jekyll/issues/2346
collections:
  engineer:
    label: "Engineer Guides"
    permalink: /engineer/:path/
    output: true
#  pkifundamentals:
#    label: "Public Key Infrastructure"
#    permalink: /pki/:path/
#    output: true
  faq:
    label: "FAQ"
    permalink: /faq/:path/
    output: true



include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
